"""empty message

Revision ID: 0218dc5cde5c
Revises: 71bc1a249fe4
Create Date: 2016-05-30 18:59:27.254142

"""

# revision identifiers, used by Alembic.
revision = '0218dc5cde5c'
down_revision = '71bc1a249fe4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
