"""empty message

Revision ID: bff32de46b33
Revises: 2e36c0bafd45
Create Date: 2016-05-30 16:13:37.911354

"""

# revision identifiers, used by Alembic.
revision = 'bff32de46b33'
down_revision = '2e36c0bafd45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_ip', sa.String(length=255), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('client')
    op.drop_table('user')
    op.drop_table('token')
    op.drop_table('grant')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('redirect_uri', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.Column('_scopes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], [u'client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=40), nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.Column('_scopes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], [u'client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('description', sa.VARCHAR(length=400), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=40), nullable=True),
    sa.Column('client_secret', sa.VARCHAR(length=55), nullable=False),
    sa.Column('is_confidential', sa.BOOLEAN(), nullable=True),
    sa.Column('redirect_uris_text', sa.TEXT(), nullable=True),
    sa.Column('default_scopes_text', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('roles')
    ### end Alembic commands ###
