"""empty message

Revision ID: eb9ba50f86d1
Revises: d9c3b153a122
Create Date: 2016-05-31 13:24:34.290396

"""

# revision identifiers, used by Alembic.
revision = 'eb9ba50f86d1'
down_revision = 'd9c3b153a122'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thingy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('image_storage_type', sa.String(length=255), nullable=True),
    sa.Column('image_storage_bucket_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thingy')
    ### end Alembic commands ###
